baseURL = "https://snayp.github.io/"
title = "сельский тестер"
ignoreErrors = ["error-remote-getjson", "error-disable-taxonomy"]
languageCode = ["ru", "en"]
defaultContentLanguage = "ru"
defaultContentLanguageInSubdir = false
disableLanguages = ["en"]
# paginatepath = "страница"
enableInlineShortcodes = true
canonifyURLs = true
relativeURLs = true
enableEmoji = true
prettyURLs = true
footnoteReturnLinkContents = "<sup>^</sup>"
ignoreFiles = ["\\.ipynb$", ".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
disableKinds = ["taxonomy"]
refLinksErrorLevel = "ERROR"
refLinksNotFoundURL = "/"

removePathAccents = true
disableAliases = true
# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  publication_type = "publication_types"

[outputs]
  home = [ "HTML", "RSS", "JSON", "WebAppManifest" ]
  section = [ "HTML", "RSS" ]

[mediaTypes."application/manifest+json"]
  suffixes = ["webmanifest"]

[outputFormats.WebAppManifest]
  mediaType = "application/manifest+json"
  rel = "manifest"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      footnote = true
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true  
      xhtml = false
  [markup.highlight]
    anchorLineNos = false
    codeFences = false
    guessSyntax = true
    hl_Lines = ""
    lineAnchors = ""
    lineNumbersInTable = false
    style = "dracula"
    tabWidth = 2
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[imaging]
  resampleFilter = "lanczos"
  quality = 90
  anchor = "smart" 

[permalinks]
  # categories = "/категория/:slug/"      # required
  # tags = "/тема/:slug/"                 # required
  pages = "/:slug/"
  # authors = "/:slug/"

[related]
  includeNewer = false
  threshold = 30
  toLower = true

  [[related.indices]]
    name = "categories"
    weight = 40

  [[related.indices]]
    name = "tags"
    weight = 60

  [[related.indices]]
    name = "authors"
    weight = 80

[module]
  [[module.imports]]
    disable = false
    path = "github.com/wowchemy/wowchemy-hugo-modules/wowchemy"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"