baseURL = "https://snayp.github.io/"
title = "сельский тестер"
ignoreErrors = ["error-remote-getjson", "error-disable-taxonomy"]
languageCode = ["ru", "en"]
defaultContentLanguage = "ru"
# defaultContentLanguageInSubdir = true
disableLanguages = ["en"]
# paginatepath = "страница"
enableInlineShortcodes = true
canonifyURLs = true
relativeURLs = true
enableEmoji = true
prettyURLs = true
footnoteReturnLinkContents = "<sup>^</sup>"
ignoreFiles = ["\\.ipynb$", ".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
disableKinds = ["taxonomies"]
refLinksErrorLevel = "ERROR"
refLinksNotFoundURL = "/"
# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  publication_type = "publication_types"

[outputs]
  home = [ "HTML", "RSS", "JSON", "WebAppManifest" ]
  section = [ "HTML", "RSS" ]

[mediaTypes."application/manifest+json"]
  suffixes = ["webmanifest"]

[outputFormats.WebAppManifest]
  mediaType = "application/manifest+json"
  rel = "manifest"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = false
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = "github"
      [markup.goldmark.parser.attribute]
        block = false
        title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[imaging]
  resampleFilter = "lanczos"
  quality = 90
  anchor = "smart" 

[permalinks]
  # categories = "/категория/:slug/"      # required
  # tags = "/тема/:slug/"                 # required
  pages = "/:slug/"
  # authors = "/:slug/"

[related]
  includeNewer = true
  threshold = 30
  toLower = true

  [[related.indices]]
    name = "categories"
    weight = 40

  [[related.indices]]
    name = "tags"
    weight = 60

  [[related.indices]]
    name = "keywords"
    weight = 80

  [[related.indices]]
    name = "authors"
    weight = 100