# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Uncomment the lines below to configure your website in a second language.
[ru]
  languageName = "русский"
  title = "Блог Снайпера"
  subtitle = "Личная страница тестера из саратовской глубинки"
  description = ""
  keywords = ""
  weight = 1
  # copyright = "{year} ( i18n \"powered_by\")"
  # layoutsDir = "layouts/ru"
  # configDir = "config/ru"
  contentDir = "content/ru/"
<<<<<<< HEAD
  paginatepath = "страница"
# Taxonomies.
# [ru.taxonomies]
#   "тема" = "темы"
#   "категория" = "категории"
#   # publication_type = "publication_types"
#   # social = "socials"
#   "автор" = "авторы"
[ru.permalinks]
  categories = "/категория/:slug/"      # required
  tags = "/тема/:slug/"  
  # posts =  "/блог/"               # required
  # pages = "/:slug/"
  # authors = "/:slug/"

# [en]
#   languageName = "english"
#   title = ""
#   subtitle = "Private view of software testing process"
#   keywords = ""
#   weight = 2
#   # copyright = ""
#   contentDir = "content/en/"
#   # configDir = "config/en"
#   # paginatepath = "страница"
# # Taxonomies.
# # [en.taxonomies]
# #   tag = "tags"
# #   category = "categories"
# #   # publication_type = "publication_types"
# #   # social = "socials"
# #   author = "authors"
# [en.permalinks]
#   categories = "/category/:slug/"      # required
#   tags = "/tag/:slug/"  
#   # posts =  "/блог/"               # required
#   # pages = "/:slug/"
#   # authors = "/:slug/"
=======

# Taxonomies.
# [ru.taxonomies]
  # "тема" = "темы"
  # "категория" = "категории"
  # publication_type = "publication_types"
  # social = "socials"
  # "автор" = "авторы"
# [ru.permalinks]
  # categories = "категория/:slug/"      # required
  # tags = "тема/:slug/"                 # required
  # pages = "/:slug/"
  # authors = "автор/:slug/"

[en]
  languageName = "english"
  subtitle = "Private view of software testing process"
  keywords = ""
  weight = 2
  # copyright = ""
  contentDir = "content/en/"
  # configDir = "config/en"

# Taxonomies.
# [en.taxonomies]
  # tag = "tags"
  # category = "categories"
  # publication_type = "publication_types"
  # social = "socials"
  # author = "authors"
# [en.permalinks]
  # categories = "category/:slug/"      # required
  # tags = "tag/:slug/"   
  # authors = "author/:slug/"
>>>>>>> feature/final-home-and-static-edition
