# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

# [[main]]
#   name = "muz"
#   url = "/музыка/"
#   weight = 32

[[social]]
  name = "GitHub"
  weight = 14
  identifier = "github"
  url = "/"

[[links]]
  name = "О блоге"
  weight = 16
  identifier = "about-me"
  url = "/about/"


# [["политика"]]
#   name = "Печеньки"
#   identifier = "политика"
#   url = "/cookies/"
#   weight = 3

# [["политика"]]
#   name = "Конфиденциальность"
#   identifier = "политика"
#   url = "/конфиденциальность/"
#   weight = 1

# [["политика"]]
#   name = "Условия использования"
#   identifier = "политика"
#   url = "/использования/"
#   weight = 2

[[main]]
  name = "блог"
  url = "блог/"
  weight = 20

[[main]]
  name = "автор"
  url = "автор/"
  weight = 45

[[main]]
  name = "содержание"
  url = "содержание/"
  weight = 40

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70

# [["анонс"]]
#   name = "год"
#   weight = 10